# Numpy and matrix math


In [6]:
# Import Numpy and create matrices

import numpy as np

A = np.array( [ [1,2,3],
                [4,5,6],
                [7,8,9] ])
print("Matrix A is")
print(A)
print('')

B = np.array( [ [6,7],
                [4,5],
                [8,9] ])
print("Matrix B is")
print(B)
print('')

C = np.array( [ [5,2,7],
                [3,5,1],
                [7,2,1] ])
print("Matrix C is")
print(C)
print('')

D = np.array( [ [5],
                [8],
                [3] ])
print("Matrix D is")
print(D)
print('')

Matrix A is
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B is
[[6 7]
 [4 5]
 [8 9]]

Matrix C is
[[5 2 7]
 [3 5 1]
 [7 2 1]]

Matrix D is
[[5]
 [8]
 [3]]



# Matrix Addition and Subtraction
To add/subtract two matrices, both matrices have to have the same number of rows and columns - so A and C above can be added/subtracted.   In Numpy, adding/subtracting matrices will result in another matrix of the same size.  Use np.add() and np.subtract() to perform the operation.

In [8]:
# Add Matrix A to Matrix C
np.add(A,C)

array([[ 6,  4, 10],
       [ 7, 10,  7],
       [14, 10, 10]])

In [9]:
# Subtract Matrix C from Matrix A
np.subtract(A,C)

array([[-4,  0, -4],
       [ 1,  0,  5],
       [ 0,  6,  8]])

# Matrix Multiplication
Number of columns in the first matrix must equal number of rows in the second matrix. If that condition isn't true, you can't do the multiplication.  Use matmul() to perform the operation.

In [11]:
# Multiply Matrix A by Matrix C
np.matmul(A,C)


array([[ 32,  18,  12],
       [ 77,  45,  39],
       [122,  72,  66]])

In [12]:
# Multiply Matrix C by Matrix D
np.matmul(C,D)

array([[62],
       [58],
       [54]])